language: node_js
node_js:
  - '12'
before_install:
    - npm i -g claudia && cd back && npm i && AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY PRODUCTION=true BASE_API_URL=$BASE_API_URL claudia update && cd ../front
script:
  - npm test
  - npm run build
before_deploy: pip install --user awscli && aws s3 rm s3://$BUCKET --recursive --region=$REGION
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $BUCKET
  local_dir: build
  skip_cleanup: true
  on:
    branch: master